; src/hal/handlers.s
; ============================================================
;  I/O handler stubs -- one per entry in games/<game>/io_map.json
; ============================================================
;
; Each handler is a tiny 68k function with C linkage. The dispatch
; table generated by `namco_amiga dispatch` calls these directly.
;
; Calling convention (m68k Amiga GCC):
;   read handlers:  d0 = full I/O address
;                   returns:    d0 = byte to read
;   write handlers: d0 = full I/O address
;                   d1 = byte to write
;                   returns:    nothing
;
; All handlers in this file are STUBS. They bump a counter and
; optionally log. The real implementations (sprite DMA, copper
; list updates, Paula audio commands) replace these one by one
; as the HAL grows.
;
; Naming convention: <handler_name>_r  for read
;                    <handler_name>_w  for write
; (matches what the dispatch generator emits)
;
; To add a new handler: write it here, declare it XDEF, that's it.
; ============================================================

        XREF    _hal_io_stub_counter

; ---- exported handler stubs (one per io_map.json entry) ----
; m68k-amigaos-gcc prefixes C identifiers with an underscore
; in the assembled output, so assembly labels that are
; referenced from C must also carry the underscore. Names
; here mirror the io_map.json handlers + a leading _.

        XDEF    _hal_tilemap_enable_w
        XDEF    _hal_watchdog_kick_r
        XDEF    _hal_mcu_reset_w
        XDEF    _hal_flip_screen_w
        XDEF    _hal_bank_switch_w
        XDEF    _hal_sound_wave_write_w
        XDEF    _hal_sound_reg_write_w
        XDEF    _hal_irq_enable_w
        XDEF    _hal_vblank_ack_r

; --- mooncrst (Galaxian-family) handler stubs ---
        XDEF    _hal_input_in0_r
        XDEF    _hal_input_in1_r
        XDEF    _hal_input_dsw0_r
        XDEF    _hal_port_a000_w
        XDEF    _hal_sound_ctrl_w
        XDEF    _hal_port_b000_w
        XDEF    _hal_sound_pitch_w

        SECTION code,CODE

; Generic stub: bumps the dispatch counter, returns 0xff for reads.
; All handlers below use this as their body. The real HAL replaces
; individual handlers as features come online.

; --- Write stub: d0=addr, d1=val ---
_hal_tilemap_enable_w:
_hal_mcu_reset_w:
_hal_flip_screen_w:
_hal_bank_switch_w:
_hal_sound_wave_write_w:
_hal_sound_reg_write_w:
_hal_irq_enable_w:
_hal_port_a000_w:
_hal_sound_ctrl_w:
_hal_port_b000_w:
_hal_sound_pitch_w:
        addq.l  #1,_hal_io_stub_counter   ; bump global counter
        rts

; --- Read stub: d0=addr, returns d0=val ---
_hal_watchdog_kick_r:
_hal_vblank_ack_r:
_hal_input_in0_r:
_hal_input_in1_r:
_hal_input_dsw0_r:
        addq.l  #1,_hal_io_stub_counter
        moveq   #-1,d0                    ; return 0xff (idle bus)
        rts

        END
