#!/usr/bin/env python3
"""Generate z80jmptab.s -- the Z80-address -> 68k-label dispatch table used to
resolve `jp (hl)` computed jumps (jump tables) in the transcode.

z80268k can't resolve data-driven indirect jumps, so z80fixup turns `jp (hl)`
into an index into this table. We build it from every `l_XXXX:` label in the
transcode: table[0xXXXX] = &l_XXXX. Z80 ROM is 0x0000-0x3fff, so the table has
0x4000 long entries. Unlabeled addresses point at z80jmp_bad (a safe stub).

Usage: gen_jmptab.py mooncrst.68k > z80jmptab.s
"""
import sys, re

labels = set()
for line in open(sys.argv[1]):
    m = re.match(r'^l_([0-9a-fA-F]{4}):', line)
    if m:
        labels.add(int(m.group(1), 16))

out = []
out.append('| z80jmptab.s -- generated by tools/gen_jmptab.py (do not edit)')
out.append('\t.text')
out.append('\t.global\tz80_ret')
out.append('z80_ret:')
out.append('\tcmp.l\t#l_0000,(a7)')
out.append('\tbcs.s\tz80_ret16')
out.append('\tcmp.l\t#z80_ret,(a7)')
out.append('\tbcc.s\tz80_ret16')
out.append('\trts')
out.append('z80_ret16:')
out.append('\tmoveq\t#0,d7')
out.append('\tmove.w\t(a7)+,d7')
out.append('\tand.l\t#0x3fff,d7')
out.append('\tlea\tz80jmptab,a0')
out.append('\tmove.l\t(a0,d7.l*4),a0')
out.append('\tjmp\t(a0)')
out.append('')
out.append('\t.global\tz80jmp_bad')
out.append('z80jmp_bad:')
out.append('\tjra\tz80jmp_bad\t| unlabeled jp(hl) target -- trap here')
out.append('\t.data')
out.append('\t.global\tz80jmptab')
out.append('\t.even')
out.append('z80jmptab:')
for a in range(0x4000):
    if a in labels:
        out.append(f'\t.long\tl_{a:04x}')
    else:
        out.append('\t.long\tz80jmp_bad')
sys.stdout.write('\n'.join(out) + '\n')
sys.stderr.write(f"z80jmptab: {len(labels)} labeled targets / 0x4000 entries\n")
