#!/usr/bin/env python3
"""Generate src/hal/mc_romdata.c from YOUR OWN Moon Cresta ROM set.

The Moon Cresta ROM is copyrighted (Nichibutsu) and is NOT distributed with
this project. You must legally own the ROM. Place the files here:

    games/mooncrst/roms/  epr194 epr195 epr196 epr197 epr198 epr199 epr200 epr201
    games/mooncrst/gfx/   mcs_a mcs_b mcs_c mcs_d
    games/mooncrst/mmi6331.6l            (palette PROM)

then run:  python3 tools/make_romdata.py
"""
import sys, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
G    = os.path.join(ROOT, "games", "mooncrst")

PROG = ["roms/epr194","roms/epr195","roms/epr196","roms/epr197",
        "roms/epr198","roms/epr199","roms/epr200","roms/epr201"]
CHAR = ["gfx/mcs_b","gfx/mcs_d","gfx/mcs_a","gfx/mcs_c"]   # planeSplit order
PROM = "mmi6331.6l"

def rd(rel):
    p = os.path.join(G, rel)
    if not os.path.exists(p):
        sys.exit("ERROR: missing ROM file '%s'.\n"
                 "You must supply your own Moon Cresta ROM set (not included)." % p)
    return open(p, "rb").read()

def emit(name, data):
    lines = ["const unsigned char %s[%d] = {" % (name, len(data))]
    for i in range(0, len(data), 16):
        lines.append("  " + ",".join(str(b) for b in data[i:i+16]) + ",")
    lines.append("};")
    return "\n".join(lines)

prog = b"".join(rd(f) for f in PROG)
char = b"".join(rd(f) for f in CHAR)
prom = rd(PROM)[:32]

out = os.path.join(ROOT, "src", "hal", "mc_romdata.c")
with open(out, "w") as f:
    f.write("/* AUTO-GENERATED by tools/make_romdata.py from your own Moon Cresta ROM.\n"
            " * The ROM is copyrighted (Nichibutsu) and is NOT part of this repository. */\n\n")
    f.write(emit("mc_prog", prog) + "\n")
    f.write("const unsigned long mc_prog_len = %d;\n\n" % len(prog))
    f.write(emit("mc_char", char) + "\n\n")
    f.write(emit("mc_prom", prom) + "\n")

print("wrote %s  (prog=%d char=%d prom=%d)" % (out, len(prog), len(char), len(prom)))
