# -*- mode: python ; coding: utf-8 -*-
#
# PyInstaller spec for the Moon Cresta disk builder GUI. Produces a single
# self-contained executable that bundles the ROM-free program (the Amiga exe +
# a ROM-free bootable ADF) and amitools (to write the ROM into the ADF
# in-process). Build from the repo root with:
#
#   pyinstaller tools/packager.spec --distpath gui_dist --workpath gui_build
#
# The bundled program is ROM-free -- the copyrighted ROM is only ever supplied
# by the end user at runtime and written to their chosen output folder.
#
# NOTE: paths in a PyInstaller spec are relative to the spec's directory, so we
# anchor everything on SPECPATH (= the tools/ dir injected by PyInstaller).
import os
from PyInstaller.utils.hooks import collect_submodules, collect_data_files

HERE = SPECPATH                      # tools/
ROOT = os.path.dirname(HERE)         # repo root

# ROM-free artifacts (committed under prebuilt/, regenerated by `make adf`).
datas = [
    (os.path.join(ROOT, 'prebuilt', 'mooncrst'), '.'),
    (os.path.join(ROOT, 'prebuilt', 'mooncrst.adf'), '.'),
]
# amitools (xdftool) is imported lazily inside mc_pack, so pull it in explicitly.
# machine68k (its optional 'vamos' extra) is not needed and not installed.
datas += collect_data_files('amitools')
hiddenimports = ['mc_pack'] + collect_submodules('amitools')

a = Analysis(
    [os.path.join(HERE, 'gui_packager.py')],
    pathex=[HERE],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    runtime_hooks=[],
    excludes=['machine68k'],
    noarchive=False,
)
pyz = PYZ(a.pure)
exe = EXE(
    pyz, a.scripts, a.binaries, a.datas, [],
    name='MoonCrestaDiskBuilder',
    debug=False,
    strip=False,
    upx=False,
    console=False,            # windowed GUI app
)
