# -*- mode: python ; coding: utf-8 -*-
#
# PyInstaller spec for the Moon Cresta disk builder GUI. Produces a single
# self-contained executable that bundles the ROM-free program (the Amiga exe +
# a ROM-free bootable ADF) and amitools (to write the ROM into the ADF
# in-process). Build from the repo root with:
#
#   pyinstaller tools/packager.spec --distpath gui_dist --workpath gui_build
#
# The bundled program is ROM-free -- the copyrighted ROM is only ever supplied
# by the end user at runtime and written to their chosen output folder.
#
# NOTE: paths in a PyInstaller spec are relative to the spec's directory, so we
# anchor everything on SPECPATH (= the tools/ dir injected by PyInstaller).
import os

HERE = SPECPATH                      # tools/
ROOT = os.path.dirname(HERE)         # repo root

# ROM-free artifacts (committed under prebuilt/, regenerated by `make adf`).
datas = [
    (os.path.join(ROOT, 'prebuilt', 'mooncrst'), '.'),
    (os.path.join(ROOT, 'prebuilt', 'mooncrst.adf'), '.'),
]
# xdftool (amitools.fs) is imported lazily in mc_pack; PyInstaller follows that
# import on its own. We must NOT pull in amitools.vamos -- it needs machine68k
# (the optional 'vamos' extra) which isn't installed and would abort the build.
hiddenimports = ['mc_pack', 'amitools.tools.xdftool']

a = Analysis(
    [os.path.join(HERE, 'gui_packager.py')],
    pathex=[HERE],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    runtime_hooks=[],
    excludes=['machine68k', 'amitools.vamos'],
    noarchive=False,
)
pyz = PYZ(a.pure)
exe = EXE(
    pyz, a.scripts, a.binaries, a.datas, [],
    name='MoonCrestaDiskBuilder',
    debug=False,
    strip=False,
    upx=False,
    console=False,            # windowed GUI app
)
