"""Quantize the rendered Twin Cobra attract frame (320x240 PPM) to 32 colors
and emit src/hal/tc_img.c: 5 Amiga bitplanes (320x256) + a 32-entry RGB12
palette. Lets the static image display via the proven Moon Cresta 5-plane AGA
path. Usage: python3 tools/tc_makeimg.py /tmp/twincobr_attract_raw.ppm
"""
import sys

def read_ppm(p):
    d = open(p, "rb").read(); assert d[:2] == b"P6"
    i = 2; vals = []
    while len(vals) < 3:
        while d[i] in b" \t\n\r": i += 1
        j = i
        while d[j] not in b" \t\n\r": j += 1
        vals.append(int(d[i:j])); i = j
    i += 1
    w, h, _ = vals
    px = d[i:i + w*h*3]
    return w, h, [(px[k*3], px[k*3+1], px[k*3+2]) for k in range(w*h)]

src = sys.argv[1] if len(sys.argv) > 1 else "/tmp/twincobr_attract_raw.ppm"
W, H, pix = read_ppm(src)
assert (W, H) == (320, 240), (W, H)

# popularity quantization to 32 colors (color 0 = black)
from collections import Counter
freq = Counter(pix)
chosen = [(0, 0, 0)]
for c, _ in freq.most_common():
    if c == (0, 0, 0): continue
    if c not in chosen: chosen.append(c)
    if len(chosen) >= 32: break
while len(chosen) < 32: chosen.append((0, 0, 0))

def nearest(c):
    br = 0; bd = 1 << 30
    for i, p in enumerate(chosen):
        d = (c[0]-p[0])**2 + (c[1]-p[1])**2 + (c[2]-p[2])**2
        if d < bd: bd = d; br = i
    return br
cache = {}
def idx(c):
    if c not in cache: cache[c] = nearest(c)
    return cache[c]

# framebuffer 320x256, image in rows 0..239
SCRW, SCRH, ROW, NP = 320, 256, 40, 5
planes = bytearray(ROW * SCRH * NP)
for y in range(H):
    for x in range(W):
        ci = idx(pix[y*W + x])
        byte = y*ROW + (x >> 3)
        bit = 7 - (x & 7)
        for p in range(NP):
            if (ci >> p) & 1:
                planes[p*ROW*SCRH + byte] |= (1 << bit)

pal12 = []
for (r, g, b) in chosen:
    pal12.append(((r >> 4) << 8) | ((g >> 4) << 4) | (b >> 4))

out = "src/hal/tc_img.c"
with open(out, "w") as f:
    f.write("/* tc_img.c -- GENERATED by tools/tc_makeimg.py.\n")
    f.write(" * Twin Cobra attract frame: 5 bitplanes (320x256) + 32-colour RGB12\n")
    f.write(" * palette. Rendered by the host emulation (tools/twincobr_render.py),\n")
    f.write(" * proving the full pipeline reaches the Amiga AGA display. */\n")
    f.write("const unsigned short tc_pal[32] = {\n  ")
    f.write(", ".join("0x%03x" % v for v in pal12))
    f.write("\n};\n")
    f.write("const unsigned char tc_planes[%d] = {\n" % len(planes))
    for i in range(0, len(planes), 20):
        f.write("  " + ",".join(str(b) for b in planes[i:i+20]) + ",\n")
    f.write("};\n")
print("wrote %s : %d distinct colors -> 32, planes=%d bytes" % (out, len(freq), len(planes)))
